name: tts
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.7.1
  - pandas=1.5.3
  - pip=23.0.1
  - pytest=7.2.2
  - python=3.10.9
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pytorch-lightning=1.9.4
  - scipy=1.10.1
  - sympy=1.11.1
  - tensorboard=2.12.0
  - pip:
      - -e ./
      - optuna=3.1.1
      - kaleido=0.2.1
      - numpy==1.23.5
