# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tts"
version = "1.0.0"
readme = "README.md"
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]